/*
 * UACalculatorUI.java
 *
 * Created on May 26, 2008, 3:37 PM
 */

package org.uacalc.nbui;

import java.awt.event.*;


/**
 *
 * @author  ralph
 */
public class UACalculatorUI extends javax.swing.JFrame {

    private final Actions actions;
    
    
    /** Creates new form UACalculatorUI */
    public UACalculatorUI() {
        initComponents();
        actions = new Actions(this);
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        //closes from title bar and from menu
        addWindowListener(new WindowAdapter() {
            public void windowClosing (WindowEvent e) {
              if (getActions().isDirty()) {
                if (getActions().checkSave()) {
                  System.exit(0);
                }
              }
              else {
                System.exit(0);
              }
            }
          });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        editorPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        newAlgButton = new javax.swing.JButton();
        openButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        algNameTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cardTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        descTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        opsComboBox = new javax.swing.JComboBox();
        delOpButton = new javax.swing.JButton();
        addOpButton = new javax.swing.JButton();
        opTableScrollPane = new javax.swing.JScrollPane();
        opTable = new javax.swing.JTable();
        idempotentCB = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        defaultEltComboBox = new javax.swing.JComboBox();
        algebrasPanel = new javax.swing.JPanel();
        currentAlgPanel = new javax.swing.JPanel();
        algebraPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        algListTable = new javax.swing.JTable();
        computationsPanel = new javax.swing.JPanel();
        resultPane = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        resultDescLabel = new javax.swing.JLabel();
        resultTextField = new javax.swing.JTextField();
        computationsLogPane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        computationsTable = new javax.swing.JTable();
        cancelCompButton = new javax.swing.JButton();
        clearLogButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        conPanel = new javax.swing.JPanel();
        subPanel = new javax.swing.JPanel();
        drawingPanel = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newMI = new javax.swing.JMenuItem();
        openMI = new javax.swing.JMenuItem();
        saveMI = new javax.swing.JMenuItem();
        saveAsMenu = new javax.swing.JMenu();
        uaFileMI = new javax.swing.JMenuItem();
        algFileMI = new javax.swing.JMenuItem();
        quitMI = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        tasksMenu = new javax.swing.JMenu();
        freeAlgMI = new javax.swing.JMenuItem();
        membershipTestMI = new javax.swing.JMenuItem();
        maltsevMenu = new javax.swing.JMenu();
        distributivityMI = new javax.swing.JMenuItem();
        modularityMI = new javax.swing.JMenuItem();
        nPermMI = new javax.swing.JMenuItem();
        maltsevMI = new javax.swing.JMenuItem();
        majorityMI = new javax.swing.JMenuItem();
        pixleyMI = new javax.swing.JMenuItem();
        nuMI = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Editor", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Drawing", jPanel2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Computatiors", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Algebra", jPanel4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        newAlgButton.setText("New");
        newAlgButton.setFocusable(false);
        newAlgButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newAlgButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        newAlgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAlgButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(newAlgButton);

        openButton.setText("Open");
        openButton.setFocusable(false);
        openButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(openButton);

        jLabel1.setText("Name:");

        jLabel2.setText("Cardinality:");

        jLabel3.setText("Desc:");

        jLabel4.setText("Operations:");

        opsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Op Yet" }));
        opsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opsComboBoxActionPerformed(evt);
            }
        });

        delOpButton.setText("Del");
        delOpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delOpButtonActionPerformed(evt);
            }
        });

        addOpButton.setText("Add");
        addOpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOpButtonActionPerformed(evt);
            }
        });

        opTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Op", "Table", "Goes", "Here"
            }
        ));
        opTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        opTable.setCellSelectionEnabled(true);
        opTableScrollPane.setViewportView(opTable);

        idempotentCB.setText("Idempotent");
        idempotentCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idempotentCBActionPerformed(evt);
            }
        });

        jLabel5.setText("Default element:");

        defaultEltComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Op Yet" }));
        defaultEltComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultEltComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editorPanelLayout = new javax.swing.GroupLayout(editorPanel);
        editorPanel.setLayout(editorPanelLayout);
        editorPanelLayout.setHorizontalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addGroup(editorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(algNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(descTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(editorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delOpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addOpButton)
                .addContainerGap(300, Short.MAX_VALUE))
            .addGroup(editorPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(idempotentCB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(defaultEltComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
            .addComponent(opTableScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        editorPanelLayout.setVerticalGroup(
            editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editorPanelLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(descTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(algNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(delOpButton)
                    .addComponent(addOpButton)
                    .addComponent(opsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(opTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(editorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idempotentCB)
                    .addComponent(jLabel5)
                    .addComponent(defaultEltComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(382, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Editor", editorPanel);

        currentAlgPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Algebra Properties"));

        javax.swing.GroupLayout currentAlgPanelLayout = new javax.swing.GroupLayout(currentAlgPanel);
        currentAlgPanel.setLayout(currentAlgPanelLayout);
        currentAlgPanelLayout.setHorizontalGroup(
            currentAlgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        currentAlgPanelLayout.setVerticalGroup(
            currentAlgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        algebraPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Algebras"));

        algListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        algListTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        algListTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(algListTable);

        javax.swing.GroupLayout algebraPanelLayout = new javax.swing.GroupLayout(algebraPanel);
        algebraPanel.setLayout(algebraPanelLayout);
        algebraPanelLayout.setHorizontalGroup(
            algebraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
            .addGroup(algebraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
        );
        algebraPanelLayout.setVerticalGroup(
            algebraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
            .addGroup(algebraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(algebraPanelLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout algebrasPanelLayout = new javax.swing.GroupLayout(algebrasPanel);
        algebrasPanel.setLayout(algebrasPanelLayout);
        algebrasPanelLayout.setHorizontalGroup(
            algebrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentAlgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(algebraPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        algebrasPanelLayout.setVerticalGroup(
            algebrasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algebrasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentAlgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(algebraPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Algebras", algebrasPanel);

        resultPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        resultTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        resultTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane4.setViewportView(resultTable);

        resultDescLabel.setText("Desc:");

        javax.swing.GroupLayout resultPaneLayout = new javax.swing.GroupLayout(resultPane);
        resultPane.setLayout(resultPaneLayout);
        resultPaneLayout.setHorizontalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPaneLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(resultDescLabel)
                .addGap(18, 18, 18)
                .addComponent(resultTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(resultPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        resultPaneLayout.setVerticalGroup(
            resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPaneLayout.createSequentialGroup()
                .addGroup(resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultDescLabel)
                    .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
            .addGroup(resultPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(resultPaneLayout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        computationsLogPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Tasks"));

        computationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        computationsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(computationsTable);

        cancelCompButton.setText("Cancel");
        cancelCompButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelCompButtonActionPerformed(evt);
            }
        });

        clearLogButton.setText("Clear");
        clearLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogButtonActionPerformed(evt);
            }
        });

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane3.setViewportView(logTextArea);

        javax.swing.GroupLayout computationsLogPaneLayout = new javax.swing.GroupLayout(computationsLogPane);
        computationsLogPane.setLayout(computationsLogPaneLayout);
        computationsLogPaneLayout.setHorizontalGroup(
            computationsLogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computationsLogPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(computationsLogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(computationsLogPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(computationsLogPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(computationsLogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelCompButton)
                    .addComponent(clearLogButton))
                .addContainerGap())
        );
        computationsLogPaneLayout.setVerticalGroup(
            computationsLogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computationsLogPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(computationsLogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(computationsLogPaneLayout.createSequentialGroup()
                        .addComponent(cancelCompButton)
                        .addGap(45, 45, 45))
                    .addGroup(computationsLogPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(computationsLogPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(computationsLogPaneLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(clearLogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(computationsLogPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(484, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout computationsPanelLayout = new javax.swing.GroupLayout(computationsPanel);
        computationsPanel.setLayout(computationsPanelLayout);
        computationsPanelLayout.setHorizontalGroup(
            computationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(resultPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(computationsLogPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        computationsPanelLayout.setVerticalGroup(
            computationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(computationsPanelLayout.createSequentialGroup()
                .addComponent(resultPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(computationsLogPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Computations", computationsPanel);

        javax.swing.GroupLayout conPanelLayout = new javax.swing.GroupLayout(conPanel);
        conPanel.setLayout(conPanelLayout);
        conPanelLayout.setHorizontalGroup(
            conPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        conPanelLayout.setVerticalGroup(
            conPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Con", conPanel);

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Sub", subPanel);

        jToolBar2.setRollover(true);

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton1);

        jButton2.setText("jButton2");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton2);

        jButton7.setText("jButton7");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton7);

        jButton8.setText("jButton8");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton8);

        javax.swing.GroupLayout drawingPanelLayout = new javax.swing.GroupLayout(drawingPanel);
        drawingPanel.setLayout(drawingPanelLayout);
        drawingPanelLayout.setHorizontalGroup(
            drawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        drawingPanelLayout.setVerticalGroup(
            drawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawingPanelLayout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(634, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Drawing", drawingPanel);

        fileMenu.setText("File");

        newMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/uacalc/ui/images/New16.gif"))); // NOI18N
        newMI.setText("New");
        newMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMIActionPerformed(evt);
            }
        });
        fileMenu.add(newMI);

        openMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/uacalc/ui/images/Open16.gif"))); // NOI18N
        openMI.setText("Open");
        openMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMIActionPerformed(evt);
            }
        });
        fileMenu.add(openMI);

        saveMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/uacalc/ui/images/Save16.gif"))); // NOI18N
        saveMI.setText("Save");
        saveMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMIActionPerformed(evt);
            }
        });
        fileMenu.add(saveMI);

        saveAsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/uacalc/ui/images/SaveAs16.gif"))); // NOI18N
        saveAsMenu.setText("Save As");

        uaFileMI.setText("ua file (new format)");
        uaFileMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaFileMIActionPerformed(evt);
            }
        });
        saveAsMenu.add(uaFileMI);

        algFileMI.setText("alg file (old format)");
        algFileMI.setToolTipText("not yet implemented");
        algFileMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algFileMIActionPerformed(evt);
            }
        });
        saveAsMenu.add(algFileMI);

        fileMenu.add(saveAsMenu);

        quitMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        quitMI.setText("Quit");
        quitMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMIActionPerformed(evt);
            }
        });
        fileMenu.add(quitMI);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");
        jMenuBar1.add(editMenu);

        tasksMenu.setText("Tasks");

        freeAlgMI.setText("Free Algebra");
        freeAlgMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeAlgMIActionPerformed(evt);
            }
        });
        tasksMenu.add(freeAlgMI);

        membershipTestMI.setText("B in V(A) ?");
        membershipTestMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membershipTestMIActionPerformed(evt);
            }
        });
        tasksMenu.add(membershipTestMI);

        jMenuBar1.add(tasksMenu);

        maltsevMenu.setText("Maltsev");

        distributivityMI.setText("Distributivity");
        distributivityMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributivityMIActionPerformed(evt);
            }
        });
        maltsevMenu.add(distributivityMI);

        modularityMI.setText("Modularity");
        modularityMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modularityMIActionPerformed(evt);
            }
        });
        maltsevMenu.add(modularityMI);

        nPermMI.setText("n-Permutability");
        nPermMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nPermMIActionPerformed(evt);
            }
        });
        maltsevMenu.add(nPermMI);

        maltsevMI.setText("Maltsev term");
        maltsevMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maltsevMIActionPerformed(evt);
            }
        });
        maltsevMenu.add(maltsevMI);

        majorityMI.setText("Majority term");
        majorityMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majorityMIActionPerformed(evt);
            }
        });
        maltsevMenu.add(majorityMI);

        pixleyMI.setText("Pixley term");
        pixleyMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pixleyMIActionPerformed(evt);
            }
        });
        maltsevMenu.add(pixleyMI);

        nuMI.setText("near unanimity term");
        nuMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuMIActionPerformed(evt);
            }
        });
        maltsevMenu.add(nuMI);

        jMenuBar1.add(maltsevMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
private void cancelCompButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCompButtonActionPerformed
  getComputationsController().cancelCurrentTask();
}//GEN-LAST:event_cancelCompButtonActionPerformed

private void clearLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLogButtonActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_clearLogButtonActionPerformed

private void quitMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMIActionPerformed
    getActions().quit();
}//GEN-LAST:event_quitMIActionPerformed

private void newMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMIActionPerformed
  getAlgebraEditorController().makeNewAlgebra();
}//GEN-LAST:event_newMIActionPerformed

private void openMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMIActionPerformed
// TODO add your handling code here:
    getActions().open();
}//GEN-LAST:event_openMIActionPerformed

private void uaFileMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uaFileMIActionPerformed
  getActions().saveAs(org.uacalc.io.ExtFileFilter.UA_EXT);
}//GEN-LAST:event_uaFileMIActionPerformed

private void algFileMIActionPerformed(java.awt.event.ActionEvent evt) {                                       
  getActions().saveAs(org.uacalc.io.ExtFileFilter.ALG_EXT);
}                                       

private void newAlgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAlgButtonActionPerformed
  getAlgebraEditorController().makeNewAlgebra();
}//GEN-LAST:event_newAlgButtonActionPerformed

private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
  getActions().open();
}//GEN-LAST:event_openButtonActionPerformed

private void addOpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOpButtonActionPerformed
  getAlgebraEditorController().addOp();
}//GEN-LAST:event_addOpButtonActionPerformed

private void idempotentCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idempotentCBActionPerformed
  getAlgebraEditorController().setIdempotent(idempotentCB.isSelected());
}//GEN-LAST:event_idempotentCBActionPerformed

private void opsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opsComboBoxActionPerformed
  getAlgebraEditorController().setCurrentOp();  
}//GEN-LAST:event_opsComboBoxActionPerformed

private void delOpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delOpButtonActionPerformed
  getAlgebraEditorController().deleteOp();
}//GEN-LAST:event_delOpButtonActionPerformed

private void defaultEltComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultEltComboBoxActionPerformed
  getAlgebraEditorController().defaultEltChangeHandler();
}//GEN-LAST:event_defaultEltComboBoxActionPerformed

private void saveMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMIActionPerformed
  getActions().save();
}//GEN-LAST:event_saveMIActionPerformed

private void freeAlgMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeAlgMIActionPerformed
  getComputationsController().setupFreeAlgebraTask();
}//GEN-LAST:event_freeAlgMIActionPerformed

private void membershipTestMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membershipTestMIActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_membershipTestMIActionPerformed

private void distributivityMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributivityMIActionPerformed
  getComputationsController().setupJonssonTermsTask();
}//GEN-LAST:event_distributivityMIActionPerformed

private void modularityMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modularityMIActionPerformed
  getComputationsController().setupGummTermsTask();
}//GEN-LAST:event_modularityMIActionPerformed

private void nPermMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nPermMIActionPerformed
  getComputationsController().setupHagemannMitschkeTermsTask();
}//GEN-LAST:event_nPermMIActionPerformed

private void nuMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuMIActionPerformed
  getComputationsController().setupNUTermTask();
}//GEN-LAST:event_nuMIActionPerformed

private void maltsevMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maltsevMIActionPerformed
  getComputationsController().setupMalcevTermTask();
}//GEN-LAST:event_maltsevMIActionPerformed

private void majorityMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majorityMIActionPerformed
  getComputationsController().setupMajorityTermTask();
}//GEN-LAST:event_majorityMIActionPerformed

private void pixleyMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pixleyMIActionPerformed
  getComputationsController().setupPixleyTermTask();
}//GEN-LAST:event_pixleyMIActionPerformed

  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
          new UACalculatorUI().setVisible(true);
        }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addOpButton;
    private javax.swing.JMenuItem algFileMI;
    private javax.swing.JTable algListTable;
    private javax.swing.JTextField algNameTextField;
    private javax.swing.JPanel algebraPanel;
    private javax.swing.JPanel algebrasPanel;
    private javax.swing.JButton cancelCompButton;
    private javax.swing.JTextField cardTextField;
    private javax.swing.JButton clearLogButton;
    private javax.swing.JPanel computationsLogPane;
    private javax.swing.JPanel computationsPanel;
    private javax.swing.JTable computationsTable;
    private javax.swing.JPanel conPanel;
    private javax.swing.JPanel currentAlgPanel;
    private javax.swing.JComboBox defaultEltComboBox;
    private javax.swing.JButton delOpButton;
    private javax.swing.JTextField descTextField;
    private javax.swing.JMenuItem distributivityMI;
    private javax.swing.JPanel drawingPanel;
    private javax.swing.JMenu editMenu;
    private javax.swing.JPanel editorPanel;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem freeAlgMI;
    private javax.swing.JCheckBox idempotentCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JMenuItem majorityMI;
    private javax.swing.JMenuItem maltsevMI;
    private javax.swing.JMenu maltsevMenu;
    private javax.swing.JMenuItem membershipTestMI;
    private javax.swing.JMenuItem modularityMI;
    private javax.swing.JMenuItem nPermMI;
    private javax.swing.JButton newAlgButton;
    private javax.swing.JMenuItem newMI;
    private javax.swing.JMenuItem nuMI;
    private javax.swing.JTable opTable;
    private javax.swing.JScrollPane opTableScrollPane;
    private javax.swing.JButton openButton;
    private javax.swing.JMenuItem openMI;
    private javax.swing.JComboBox opsComboBox;
    private javax.swing.JMenuItem pixleyMI;
    private javax.swing.JMenuItem quitMI;
    private javax.swing.JLabel resultDescLabel;
    private javax.swing.JPanel resultPane;
    private javax.swing.JTable resultTable;
    private javax.swing.JTextField resultTextField;
    private javax.swing.JMenu saveAsMenu;
    private javax.swing.JMenuItem saveMI;
    private javax.swing.JPanel subPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JMenu tasksMenu;
    private javax.swing.JMenuItem uaFileMI;
    // End of variables declaration//GEN-END:variables


  public Actions getActions() {
    return actions;
  }
  
  public AlgebraEditorController getAlgebraEditorController() {
    return getActions().getAlgebraEditorController();
  }
  
  public ComputationsController getComputationsController() {
    return getActions().getComputationsController();
  }

  public javax.swing.JTextField getAlgNameTextField() {
    return algNameTextField;
  }

  public javax.swing.JPanel getAlgebraPanel() {
    return algebraPanel;
  }

  public javax.swing.JPanel getAlgebrasPanel() {
    return algebrasPanel;
  }

  public javax.swing.JTextField getCardTextField() {
    return cardTextField;
  }

  public javax.swing.JPanel getComputationsLogPane() {
    return computationsLogPane;
  }

  public javax.swing.JPanel getComputationsPanel() {
    return computationsPanel;
  }

  public javax.swing.JTable getComputationsTable() {
    return computationsTable;
  }

  public javax.swing.JPanel getConPanel() {
    return conPanel;
  }

  public javax.swing.JPanel getCurrentAlgPanel() {
    return currentAlgPanel;
  }

  public javax.swing.JComboBox getDefaultEltComboBox() {
    return defaultEltComboBox;
  }

  public javax.swing.JTextField getDescTextField() {
    return descTextField;
  }

  public javax.swing.JPanel getDrawingPanel() {
    return drawingPanel;
  }

  public javax.swing.JPanel getEditorPanel() {
    return editorPanel;
  }

  public javax.swing.JCheckBox getIdempotentCB() {
    return idempotentCB;
  }

  public javax.swing.JTextArea getLogTextArea() {
    return logTextArea;
  }

  public javax.swing.JMenuItem getNewMI() {
    return newMI;
  }

  public javax.swing.JTable getOpTable() {
    return opTable;
  }

  public javax.swing.JComboBox getOpsComboBox() {
    return opsComboBox;
  }

  public javax.swing.JPanel getResultPane() {
    return resultPane;
  }

  public javax.swing.JTextField getResultTextField() {
    return resultTextField;
  }

  public javax.swing.JTable getResultTable() {
    return resultTable;
  }

  public javax.swing.JPanel getSubPanel() {
    return subPanel;
  }

  public void beep() {
    java.awt.Toolkit.getDefaultToolkit().beep();
  }

  public javax.swing.JScrollPane getOpTableScrollPane() {
    return opTableScrollPane;
  }

  public void setOpTableScrollPane(javax.swing.JScrollPane opTableScrollPane) {
    this.opTableScrollPane = opTableScrollPane;
  }

    public void setAlgListTable(javax.swing.JTable algListTable) {
        this.algListTable = algListTable;
    }

    public javax.swing.JTable getAlgListTable() {
        return algListTable;
    }

    public javax.swing.JMenuItem getDistributivityMI() {
        return distributivityMI;
    }

    public void setDistributivityMI(javax.swing.JMenuItem distributivityMI) {
        this.distributivityMI = distributivityMI;
    }

    public javax.swing.JMenuItem getModularityMI() {
        return modularityMI;
    }

    public void setModularityMI(javax.swing.JMenuItem modularityMI) {
        this.modularityMI = modularityMI;
    }

    public javax.swing.JMenuItem getNPermMI() {
        return nPermMI;
    }

    public void setNPermMI(javax.swing.JMenuItem nPermMI) {
        this.nPermMI = nPermMI;
    }

    public javax.swing.JTabbedPane getTabbedPane() {
        return tabbedPane;
    }

    public void setResultTable(javax.swing.JTable resultTable) {
        this.resultTable = resultTable;
    }
  
}
